#!/usr/bin/env bash

# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

ANSIBLE_COLLECTION_COMMONS_VERSION=${ANSIBLE_COLLECTION_COMMONS_VERSION:-main}
ANSIBLE_COLLECTION_SERVICES_VERSION=${ANSIBLE_COLLECTION_SERVICES_VERSION:-main}
ANSIBLE_PLAYBOOKS_MANAGER_VERSION=${ANSIBLE_PLAYBOOKS_MANAGER_VERSION:-main}

ANSIBLE_COLLECTION_COMMONS_SOURCE=${ANSIBLE_COLLECTION_COMMONS_SOURCE:-git+https://github.com/osism/ansible-collection-commons}
ANSIBLE_COLLECTION_SERVICES_SOURCE=${ANSIBLE_COLLECTION_SERVICES_SOURCE:-git+https://github.com/osism/ansible-collection-services}
ANSIBLE_PLAYBOOKS_MANAGER_SOURCE=${ANSIBLE_PLAYBOOKS_MANAGER_SOURCE:-git+https://github.com/osism/ansible-playbooks-manager}

ANSIBLE_VERSION=${ANSIBLE_VERSION:-11.4.0}

INSTALL_ANSIBLE=${INSTALL_ANSIBLE:-true}
INSTALL_ANSIBLE_ROLES=${INSTALL_ANSIBLE_ROLES:-true}
VENV_PATH=${VENV_PATH:-venv}
VENV_PYTHON_BIN=${VENV_PYTHON_BIN:-python3}

RUNDIR="$(dirname "$(readlink -f "$0")")"
cd "$RUNDIR" || exit 1


if [[ "$#" -lt 1 ]]; then
    echo "usage: $0 PLAYBOOK [ANSIBLEARGS...]"
    exit 1
fi

playbook=$1
shift

# ---------------------------------------------------------------------------
# Seed-container execution path.
#
# SEED_CONTAINER selects how the playbook runs:
#   auto  (default) run in the osism/seed container when a container engine is
#                   up; otherwise fall back to the local venv path below
#   true            force the container (error if the engine command is missing)
#   false           force the local venv path
# The image is assembled from SEED_CONTAINER_REGISTRY/IMAGE:TAG; an empty
# registry drops the leading segment (for a locally-built, unqualified image).
# ---------------------------------------------------------------------------
SEED_CONTAINER=${SEED_CONTAINER:-auto}
CONTAINER_ENGINE=${CONTAINER_ENGINE:-docker}

SEED_CONTAINER_REGISTRY=${SEED_CONTAINER_REGISTRY-registry.osism.tech}
SEED_CONTAINER_IMAGE=${SEED_CONTAINER_IMAGE:-osism/seed}
SEED_CONTAINER_TAG=${SEED_CONTAINER_TAG:-latest}
SEED_CONTAINER_PULL=${SEED_CONTAINER_PULL:-always}
SEED_CONTAINER_MOUNT_OPTS=${SEED_CONTAINER_MOUNT_OPTS:-}

run_in_container=false
case "$SEED_CONTAINER" in
    false)
        ;;
    true)
        if ! command -v "$CONTAINER_ENGINE" >/dev/null 2>&1; then
            echo >&2 "ERROR: SEED_CONTAINER=true but container engine '$CONTAINER_ENGINE' not found on PATH"
            exit 1
        fi
        run_in_container=true
        ;;
    auto)
        if command -v "$CONTAINER_ENGINE" >/dev/null 2>&1 && "$CONTAINER_ENGINE" info >/dev/null 2>&1; then
            run_in_container=true
        fi
        ;;
    *)
        echo >&2 "ERROR: invalid SEED_CONTAINER value '$SEED_CONTAINER' (expected one of: auto, true, false)"
        exit 1
        ;;
esac

if [[ $run_in_container == "true" ]]; then
    ROOT="$(readlink -f "$RUNDIR/../..")"
    image_ref="${SEED_CONTAINER_REGISTRY:+$SEED_CONTAINER_REGISTRY/}$SEED_CONTAINER_IMAGE:$SEED_CONTAINER_TAG"

    container_args=(run --rm -i)
    [[ -t 0 ]] && container_args+=(-t)
    container_args+=(--pull "$SEED_CONTAINER_PULL")
    container_args+=(-v "$ROOT:/opt/configuration$SEED_CONTAINER_MOUNT_OPTS")

    # Forward selected Ansible/OSISM variables, but only when set in the
    # caller's environment. Emitting VAR=value (not a bare VAR) keeps the value
    # in the engine's argv rather than relying on the engine inheriting our
    # environment.
    for var in ANSIBLE_USER ANSIBLE_ASK_PASS ANSIBLE_BECOME_ASK_PASS \
               ANSIBLE_ASK_VAULT_PASS ANSIBLE_VAULT_PASSWORD_FILE \
               ANSIBLE_SSH_ARGS MANAGER_VERSION; do
        if [[ -n "${!var+x}" ]]; then
            container_args+=(-e "$var=${!var}")
        fi
    done

    # Vault default: only when the caller did not set ANSIBLE_VAULT_PASSWORD_FILE
    # and the configuration repository ships the .vault_pass wrapper.
    if [[ -z "${ANSIBLE_VAULT_PASSWORD_FILE+x}" && -e "$ROOT/environments/.vault_pass" ]]; then
        container_args+=(-e "ANSIBLE_VAULT_PASSWORD_FILE=/opt/configuration/environments/.vault_pass")
    fi

    container_args+=("$image_ref" "$playbook" "$@")

    exec "$CONTAINER_ENGINE" "${container_args[@]}"
fi

if [[ $INSTALL_ANSIBLE == "true" ]]; then
    if [[ ! -e $VENV_PATH/bin/activate ]]; then
        $VENV_PYTHON_BIN -m venv "$VENV_PATH"

        # shellcheck source=/dev/null
        source "$VENV_PATH/bin/activate"
        pip3 install uv
        uv pip install -r requirements.txt
        uv pip install "ansible==$ANSIBLE_VERSION"

    else

        # shellcheck source=/dev/null
        source "$VENV_PATH/bin/activate"

    fi
fi

command -v ansible-playbook >/dev/null 2>&1 || { echo >&2 "ansible-playbook not installed"; exit 1; }
command -v ansible-galaxy >/dev/null 2>&1 || { echo >&2 "ansible-galaxy not installed"; exit 1; }

configured_branch="$(grep -E "^configuration_git_version:"  "$RUNDIR/configuration.yml" | sed 's/^..*:[ ]*//')"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$configured_branch" != "$current_branch" ];then
   echo "ERROR: Configured branch '$configured_branch' and current checkout-branch '$current_branch' are not the same!"
   echo "(see ${RUNDIR}/configuration.yml, configuration_git_version)"
   exit 1
fi

ANSIBLE_USER=${ANSIBLE_USER:-dragon}
CLEANUP=${CLEANUP:-false}

cleanup () {
    if [[ $CLEANUP == "true" ]]; then
        rm id_rsa.operator
        rm -rf "$VENV_PATH"
    fi
}
trap cleanup ERR EXIT

if [[ $INSTALL_ANSIBLE_ROLES == "true" ]]; then
    ansible-galaxy collection install -f "${ANSIBLE_COLLECTION_COMMONS_SOURCE},${ANSIBLE_COLLECTION_COMMONS_VERSION}"
    ansible-galaxy collection install -f "${ANSIBLE_COLLECTION_SERVICES_SOURCE},${ANSIBLE_COLLECTION_SERVICES_VERSION}"
    ansible-galaxy collection install -f "${ANSIBLE_PLAYBOOKS_MANAGER_SOURCE},${ANSIBLE_PLAYBOOKS_MANAGER_VERSION}"
fi

if [[ "$playbook" == "noop" ]]; then
    exit 0
fi

if [[ -e .vault_pass ]]; then
    VAULT=.vault_pass
elif [[ \
      $(head -1 secrets.yml | grep -v -q \$ANSIBLE_VAULT || echo 1) == 1 || \
      $(head -1 ../secrets.yml | grep -v -q \$ANSIBLE_VAULT || echo 1) == 1 || \
      $(head -1 ../infrastructure/secrets.yml | grep -v -q \$ANSIBLE_VAULT || echo 1) == 1 \
   ]]; then
    export ANSIBLE_ASK_VAULT_PASS=true
fi

if [[ ! -e id_rsa.operator ]]; then
    ansible-playbook \
        -i localhost, \
        -e @../secrets.yml \
        -e "keypair_dest=$(pwd)/id_rsa.operator" \
        ${VAULT:+--vault-password-file "$VAULT"} \
        osism.manager.keypair "$@" || exit $?
fi

if [[ $playbook != "operator" && $ANSIBLE_USER != "dragon" ]]; then
   echo -e "\nWARNING: ANSIBLE_USER is currently set to '$ANSIBLE_USER'. Normally ANSIBLE_USER should be set to 'dragon' for the play '$playbook'.\n"
fi

if [[ $playbook == "k8s" || $playbook == "netbox" || $playbook == "traefik" ]]; then
    ansible-playbook \
        --private-key id_rsa.operator \
        -i hosts \
        -e @../images.yml \
        -e @../configuration.yml \
        -e @../secrets.yml \
        -e @../infrastructure/images.yml \
        -e @../infrastructure/configuration.yml \
        -e @../infrastructure/secrets.yml \
        -e @images.yml \
        -e @configuration.yml \
        -e @secrets.yml \
        -u "$ANSIBLE_USER" \
        ${VAULT:+--vault-password-file "$VAULT"} \
        osism.manager."$playbook" "$@" || exit $?
elif [[ $playbook == "operator" ]]; then
    if [[ $ANSIBLE_ASK_PASS == "True" ]]; then
        ansible-playbook \
            -i hosts \
            -e @../images.yml \
            -e @../configuration.yml \
            -e @../secrets.yml \
            -e @images.yml \
            -e @configuration.yml \
            -e @secrets.yml \
            -u "$ANSIBLE_USER" \
            ${VAULT:+--vault-password-file "$VAULT"} \
            osism.manager."$playbook" "$@" || exit $?
    else
        ansible-playbook \
            --private-key id_rsa.operator \
            -i hosts \
            -e @../images.yml \
            -e @../configuration.yml \
            -e @../secrets.yml \
            -e @images.yml \
            -e @configuration.yml \
            -e @secrets.yml \
            -u "$ANSIBLE_USER" \
            ${VAULT:+--vault-password-file "$VAULT"} \
            osism.manager."$playbook" "$@" || exit $?
    fi
else
    ansible-playbook \
        --private-key id_rsa.operator \
        -i hosts \
        -e @../images.yml \
        -e @../configuration.yml \
        -e @../secrets.yml \
        -e @images.yml \
        -e @configuration.yml \
        -e @secrets.yml \
        -u "$ANSIBLE_USER" \
        ${VAULT:+--vault-password-file "$VAULT"} \
        osism.manager."$playbook" "$@" || exit $?
fi
