---
- job:
    name: generics-tox-test-stable
    parent: tox
    vars:
      tox_envlist: test
      tox_environment:
        MANAGER_VERSION: "9.1.0"

- job:
    name: generics-tox-test-stable-legacy
    parent: tox
    vars:
      tox_envlist: test
      tox_environment:
        MANAGER_VERSION: "9.0.0"

- job:
    name: generics-tox-test-latest
    parent: tox
    vars:
      tox_envlist: test
      tox_environment:
        MANAGER_VERSION: "latest"

- job:
    name: generics-tox-check
    parent: tox
    vars:
      tox_envlist: check

- job:
    name: generics-tox-check-kolla
    parent: tox
    vars:
      tox_envlist: check-kolla

- job:
    name: generics-tox-seed
    parent: tox
    vars:
      tox_envlist: seed

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - generics-tox-check
        - generics-tox-check-kolla
        - generics-tox-seed
        - generics-tox-test-latest
        - generics-tox-test-stable
        - generics-tox-test-stable-legacy
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - generics-tox-check
        - generics-tox-check-kolla
        - generics-tox-seed
        - generics-tox-test-latest
        - generics-tox-test-stable
        - generics-tox-test-stable-legacy
        - check-shell-syntax
        - flake8
        - python-black
        - yamllint
